=== jadujoel/audio-atlas-architect/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "cache": {
      "type": "string"
    },
    "banks": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/BankConfig"
      }
    },
    "rootdir": {
      "type": "string"
    },
    "outdir": {
      "type": "string"
    },
    "legacy_support": {
      "type": "boolean"
    },
    "concurrency": {
      "type": "number"
    }
  },
  "required": ["name", "cache", "banks", "rootdir", "outdir", "legacy_support"],
  "definitions": {
    "BankConfig": {
      "type": "object",
      "properties": {
        "base": {
          "type": "string"
        },
        "rootdir": {
          "type": "string"
        },
        "outdir": {
          "type": "string"
        },
        "media": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/EntryConfig"
          }
        },
        "extends": {
          "type": "string"
        }
      },
      "required": ["base", "rootdir", "outdir", "media"]
    },
    "EntryConfig": {
      "type": "object",
      "properties": {
        "channels": {
          "type": "integer",
          "enum": [1, 2]
        },
        "bitrate": {
          "type": "number"
        },
        "localization": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "extends": {
          "type": "string"
        }
      },
      "required": ["channels", "bitrate", "localization"]
    }
  }
}

=== jadujoel/audio-atlas-architect/config.json
{
  "$schema": "./schema.json",
  "name": "sounds",
  "concurrency": 4,
  "cache": ".cache",
  "rootdir": "sounds",
  "outdir": "public/assets/sounds",
  "banks": {
    "common": {
      "base": "/assets/sounds/common",
      "rootdir": "sounds/common",
      "outdir": "public/assets/sounds/common",
      "media": {
        "effects": {
          "channels": 2,
          "bitrate": 64,
          "localization": []
        }
      }
    },
    "unicorn": {
      "base": "/assets/sounds/unicorn",
      "rootdir": "sounds/unicorn",
      "outdir": "public/assets/sounds/unicorn",
      "extends": "common",
      "media": {
        "music": {
          "channels": 2,
          "bitrate": 80,
          "localization": []
        },
        "effects": {
          "channels": 2,
          "bitrate": 64,
          "localization": []
        },
        "voice": {
          "channels": 1,
          "bitrate": 32,
          "localization": ["*"]
        }
      }
    }
  },
  "legacy_support": true
}
